// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl6usAKGmUxoVFz8bmD52kcsvJ70EVV_U',
    appId: '1:1004171793706:web:5d487ba765fc74b2387a53',
    messagingSenderId: '1004171793706',
    projectId: 'mynotes-animesh',
    authDomain: 'mynotes-animesh.firebaseapp.com',
    storageBucket: 'mynotes-animesh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl_3Ur-LUGI40ZmgQbQRpwY7A2agGwKCA',
    appId: '1:1004171793706:android:d15b5ba49f36f114387a53',
    messagingSenderId: '1004171793706',
    projectId: 'mynotes-animesh',
    storageBucket: 'mynotes-animesh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC2NW9yS8OLMHLNkDP6X0WMU7NFjLHIEg',
    appId: '1:1004171793706:ios:c04bd5c6251caabe387a53',
    messagingSenderId: '1004171793706',
    projectId: 'mynotes-animesh',
    storageBucket: 'mynotes-animesh.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC2NW9yS8OLMHLNkDP6X0WMU7NFjLHIEg',
    appId: '1:1004171793706:ios:c04bd5c6251caabe387a53',
    messagingSenderId: '1004171793706',
    projectId: 'mynotes-animesh',
    storageBucket: 'mynotes-animesh.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl6usAKGmUxoVFz8bmD52kcsvJ70EVV_U',
    appId: '1:1004171793706:web:ded0acae0c5eeb1e387a53',
    messagingSenderId: '1004171793706',
    projectId: 'mynotes-animesh',
    authDomain: 'mynotes-animesh.firebaseapp.com',
    storageBucket: 'mynotes-animesh.firebasestorage.app',
  );
}
